# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamavail-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamavail
  template:
    metadata:
      labels:
        app: teamavail
    spec:
      containers:
        - name: teamavail
          image: ahmed1salem/teamavailtest-web:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/output
              name: output-volume
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: output-volume
          persistentVolumeClaim:
            claimName: output-pvc
