name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # مهم: يشتغل على جهازك المحلي

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t ahmed1salem/teamavailtest-web:latest .

      # 3️⃣ Push Docker image to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: docker push ahmed1salem/teamavailtest-web:latest

      # 4️⃣ Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 5️⃣ Use Minikube context
      - name: Use minikube context
        run: kubectl config use-context minikube

      # 6️⃣ Deploy Kubernetes manifests
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/persistent-volume.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml

      # 7️⃣ Optional: Check pods and services
      - name: Check Cluster Status
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get ingress
