name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # ده المهم، عشان يشتغل على جهازك المحلي

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ahmed1salem/teamavailtest-web:latest .

      # Push Docker image to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: docker push ahmed1salem/teamavailtest-web:latest

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Use minikube context
      - name: Use minikube context
        run: kubectl config use-context minikube

      # Deploy to minikube
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Optional: Check pods status
      - name: Check Pods
        run: kubectl get pods
